[package]
name = "cli-agent-util"
version = "0.1.0"
edition = "2024"
authors = ["Niko Matsakis"]
description = "Utilities for managing CLI agents in Symposium"

[dependencies]
anyhow = { workspace = true }
which = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
